# Generated by Django 4.0.2 on 2023-03-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='actual_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
