# Generated by Django 4.0.2 on 2023-03-04 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings_service', '0002_alter_borrowing_actual_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowing',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='borrowing',
            old_name='user_id',
            new_name='customer',
        ),
    ]
