# Generated by Django 4.0.2 on 2023-03-04 15:34

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('borrowings_service', '0003_rename_book_id_borrowing_book_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='borrowing',
            constraint=models.CheckConstraint(check=models.Q(('borrow_date__gte', django.db.models.expressions.F('expected_return_date'))), name='dates_constraint'),
        ),
    ]
