# Generated by Django 4.1.7 on 2023-03-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings_service", "0008_remove_borrowing_dates_constraint_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="borrowing",
            options={"ordering": ("borrow_date",)},
        ),
    ]
